name: William Gagan
favicon: null
layout_spectrum: 1
typography_spectrum: 0.84808
title: Willyforeal Photography
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#3a3f42'
    - '#616362'
    - '#828680'
    - '#c7bfb0'
  brandStrength: 0
  lightness: 1
  saturation: 0
  rhythmicContrast: 0
purpose: []
