name: William Gagan
favicon: null
layout_spectrum: 0
typography_spectrum: 0.84808
title: Willyforeal Photography
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#030303'
    - '#020202'
    - '#040404'
    - '#040403'
  brandStrength: 1
  lightness: 0
  saturation: 1
  rhythmicContrast: 1
purpose: []
