name: William Gagan
favicon: null
layout_spectrum: 1
typography_spectrum: 0.84808
title: Willyforeal Photography
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#020202'
    - '#ffffff'
    - '#756045'
    - '#b2a289'
    - '#a90000'
  brandStrength: 0.5
  lightness: 0.25
  saturation: 0
  rhythmicContrast: 0
purpose: []
